spring:
  application:
    name: metroline
  servlet:
    multipart:
      enabled: true
      location: /tmp
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
graphql:
  servlet:
    actuator-metrics: true
    enabled: true
  playground:
    cdn:
      version: latest
altair:
  enabled: true
  cdn:
    enabled: false
graphiql:
  enabled: true
  cdn:
    enabled: true
    version: 0.17.5
voyager:
  enabled: true
  cdn:
    enabled: false
graphql.playground:
  enabled: true
  cdn:
    enabled: false

